import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by create next.js',
}
//nested loyout 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='text-2xl text-primary-content'>This is navbar</nav>
        {children}</body>

    </html>
  )
}
