import { Inter } from 'next/font/google'//for font
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })// store instances of the Inter font.

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by create next.js',
}
//nested loyout 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
          <main className='px-8 py-20 max-w-6xl mx-auto'> {children} </main>
        
        
       
      </body>

    </html>
  )
}
